// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TodoService manages todo items in memory
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add creates a new todo item
 * @param {string} title
 * @returns {$CancellablePromise<$models.Todo>}
 */
export function Add(title) {
    return $Call.ByID(368471028, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearCompleted removes all completed todos
 * @returns {$CancellablePromise<$models.Todo[]>}
 */
export function ClearCompleted() {
    return $Call.ByID(3284815095).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Delete removes a todo by ID
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(1271921866, id);
}

/**
 * GetAll returns all todos
 * @returns {$CancellablePromise<$models.Todo[]>}
 */
export function GetAll() {
    return $Call.ByID(851959634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetFiltered returns todos filtered by status
 * @param {string} filter
 * @returns {$CancellablePromise<$models.Todo[]>}
 */
export function GetFiltered(filter) {
    return $Call.ByID(702393000, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetStats returns statistics about todos
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function GetStats() {
    return $Call.ByID(2561327386).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Toggle toggles the completed status of a todo
 * @param {number} id
 * @returns {$CancellablePromise<$models.Todo>}
 */
export function Toggle(id) {
    return $Call.ByID(607591045, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Update updates the title of a todo
 * @param {number} id
 * @param {string} title
 * @returns {$CancellablePromise<$models.Todo>}
 */
export function Update(id, title) {
    return $Call.ByID(203246836, id, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Todo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
