// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FolderService manages folder CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Create creates a new folder.
 * @param {string} name
 * @param {string} icon
 * @param {string | null} parentID
 * @returns {$CancellablePromise<models$0.Folder>}
 */
export function Create(name, icon, parentID) {
    return $Call.ByID(354282023, name, icon, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete removes a folder and moves its notes to "All Notes".
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(4293384668, id);
}

/**
 * GetAll returns all folders with note counts.
 * @returns {$CancellablePromise<models$0.FolderWithCount[]>}
 */
export function GetAll() {
    return $Call.ByID(184731520).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Rename renames a folder.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Rename(id, name) {
    return $Call.ByID(3034356661, id, name);
}

// Private type creation functions
const $$createType0 = models$0.Folder.createFrom;
const $$createType1 = models$0.FolderWithCount.createFrom;
const $$createType2 = $Create.Array($$createType1);
