// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService manages note CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Create creates a new note and returns it.
 * @param {string} title
 * @param {string} content
 * @param {string | null} folderID
 * @returns {$CancellablePromise<models$0.Note>}
 */
export function Create(title, content, folderID) {
    return $Call.ByID(756057767, title, content, folderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete removes a note by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(400193116, id);
}

/**
 * GetAll returns all non-archived notes, optionally filtered by folder.
 * @param {string | null} folderID
 * @returns {$CancellablePromise<models$0.Note[]>}
 */
export function GetAll(folderID) {
    return $Call.ByID(586507264, folderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetArchived returns all archived notes.
 * @returns {$CancellablePromise<models$0.Note[]>}
 */
export function GetArchived() {
    return $Call.ByID(3664311887).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetByID returns a single note by ID.
 * @param {string} id
 * @returns {$CancellablePromise<models$0.Note>}
 */
export function GetByID(id) {
    return $Call.ByID(3949313365, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStats returns note statistics.
 * @returns {$CancellablePromise<models$0.NoteStats>}
 */
export function GetStats() {
    return $Call.ByID(1246791960).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Search searches notes by title or content using LIKE pattern matching.
 * @param {string} query
 * @returns {$CancellablePromise<models$0.Note[]>}
 */
export function Search(query) {
    return $Call.ByID(144441359, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Update updates an existing note with the provided fields.
 * @param {string} id
 * @param {string | null} title
 * @param {string | null} content
 * @param {string | null} folderID
 * @param {boolean | null} isPinned
 * @param {boolean | null} isArchived
 * @returns {$CancellablePromise<models$0.Note>}
 */
export function Update(id, title, content, folderID, isPinned, isArchived) {
    return $Call.ByID(1003352110, id, title, content, folderID, isPinned, isArchived).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = models$0.Note.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = models$0.NoteStats.createFrom;
