// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService provides greeting functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetWailsInfo returns information about the Wails framework
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function GetWailsInfo() {
    return $Call.ByID(2768768486).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Greet returns a greeting message for the given name.
 * This method is automatically exposed to the frontend via Wails bindings.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(1411160069, name);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
