// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * AppInfo holds application metadata and platform information.
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

/**
 * Folder represents a folder that organizes notes.
 */
export class Folder {
    /**
     * Creates a new Folder instance.
     * @param {Partial<Folder>} [$$source = {}] - The source object to create the Folder.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parent_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Folder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Folder}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Folder(/** @type {Partial<Folder>} */($$parsedSource));
    }
}

/**
 * FolderWithCount includes the note count for a folder.
 */
export class FolderWithCount {
    /**
     * Creates a new FolderWithCount instance.
     * @param {Partial<FolderWithCount>} [$$source = {}] - The source object to create the FolderWithCount.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("parent_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["parent_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("note_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["note_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderWithCount instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderWithCount}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderWithCount(/** @type {Partial<FolderWithCount>} */($$parsedSource));
    }
}

/**
 * Note represents a single note entry.
 */
export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("folder_id" in $$source)) {
            /**
             * @member
             * @type {string | null}
             */
            this["folder_id"] = null;
        }
        if (!("is_pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_pinned"] = false;
        }
        if (!("is_archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_archived"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

/**
 * NoteStats holds statistics about notes.
 */
export class NoteStats {
    /**
     * Creates a new NoteStats instance.
     * @param {Partial<NoteStats>} [$$source = {}] - The source object to create the NoteStats.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pinned"] = 0;
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["archived"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NoteStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NoteStats(/** @type {Partial<NoteStats>} */($$parsedSource));
    }
}
