// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CalculatorService demonstrates methods with multiple parameters and error handling
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Add returns the sum of two numbers
 * @param {number} a
 * @param {number} b
 * @returns {$CancellablePromise<number>}
 */
export function Add(a, b) {
    return $Call.ByID(3136481180, a, b);
}

/**
 * BatchCalculate performs multiple operations and returns results
 * @param {number} a
 * @param {number} b
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function BatchCalculate(a, b) {
    return $Call.ByID(1133031913, a, b).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Divide returns the quotient of two numbers, returns error if dividing by zero
 * @param {number} a
 * @param {number} b
 * @returns {$CancellablePromise<number>}
 */
export function Divide(a, b) {
    return $Call.ByID(1917670472, a, b);
}

/**
 * Multiply returns the product of two numbers
 * @param {number} a
 * @param {number} b
 * @returns {$CancellablePromise<number>}
 */
export function Multiply(a, b) {
    return $Call.ByID(500610509, a, b);
}

/**
 * Power returns a raised to the power of b
 * @param {number} base
 * @param {number} exponent
 * @returns {$CancellablePromise<number>}
 */
export function Power(base, exponent) {
    return $Call.ByID(3716064862, base, exponent);
}

/**
 * Sqrt returns the square root of a number, returns error if negative
 * @param {number} n
 * @returns {$CancellablePromise<number>}
 */
export function Sqrt(n) {
    return $Call.ByID(4113188903, n);
}

/**
 * Subtract returns the difference of two numbers
 * @param {number} a
 * @param {number} b
 * @returns {$CancellablePromise<number>}
 */
export function Subtract(a, b) {
    return $Call.ByID(3750567993, a, b);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
