// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CounterService demonstrates basic state management with service binding
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Decrement decreases the counter by 1 and returns the new value
 * @returns {$CancellablePromise<number>}
 */
export function Decrement() {
    return $Call.ByID(3999383778);
}

/**
 * GetCount returns the current counter value
 * @returns {$CancellablePromise<number>}
 */
export function GetCount() {
    return $Call.ByID(486895358);
}

/**
 * GetCounterInfo returns detailed information about the counter
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetCounterInfo() {
    return $Call.ByID(3142879569).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Increment increases the counter by 1 and returns the new value
 * @returns {$CancellablePromise<number>}
 */
export function Increment() {
    return $Call.ByID(1567680814);
}

/**
 * IncrementBy increases the counter by a specified amount
 * @param {number} amount
 * @returns {$CancellablePromise<number>}
 */
export function IncrementBy(amount) {
    return $Call.ByID(1986393031, amount);
}

/**
 * Reset sets the counter back to 0
 * @returns {$CancellablePromise<number>}
 */
export function Reset() {
    return $Call.ByID(3088708176);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
