// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as CalculatorService from "./calculatorservice.js";
import * as CounterService from "./counterservice.js";
export {
    CalculatorService,
    CounterService
};
